window:
  dimensions:
    columns: 140
    lines: 36
  # decorations: none

font:
  normal:
    family: MesloLGS NF
    style: Regular
  size: 13
  use_thin_strokes: true

cursor:
  style: Beam
  vi_cursor_style: Block

alt_send_esc: false

# Ayu adaptation
colors:
  # Default colors
  primary:
    background: '#27272d' # '#1f2430'
    foreground: '#cbccc6'
    bright_foreground: '#f28779'

  # Normal colors
  normal:
    black:   '#212733' #
    red:     '#ed4e4e' #
    green:   '#22df61' #
    yellow:  '#fdcc60' #
    blue:    '#60b8d6' # 
    magenta: '#ec7171' #
    cyan:    '#34d8eb' #
    white:   '#fafafa' #

  # Brightened
  bright:
    black: '#686868'
    red: '#f76868'
    green: '#23fe6e'
    yellow: '#ffd165'
    blue: '#65bddb'
    magenta: '#f17676'
    cyan: '#1be1f7'
    white: '#ffffff'

