window:
  dimensions:
    columns: 140
    lines: 36
  # decorations: none

font:
  normal:
    family: MesloLGS NF
    style: Regular
  size: 13
  use_thin_strokes: true

cursor:
  style: Beam
  vi_cursor_style: Block

alt_send_esc: false

# Colors (Dracula)
colors:
  # Default colors
  primary:
    #background: '#282a36'
    background: '#172b41'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'
